In [1]:
import pandas as pd
import yfinance as yf
import datetime as dt

# list of assets (updated with our chosen assets):
# Companies: Salesforce, HP, Lenovo, Ford, Tesla, Walmart, Target 
my_tickers = ['CRM', 'HPQ', 'LNVGY', 'F', 'TSLA', 'WMT', 'TGT']


# Assign a start date and end date for the data download, 1 year of data
start_date = dt.datetime.today() - pd.Timedelta(3650, "d")
end_date = dt.datetime.today()

In [2]:
## Now download the data using the above variables, my_port is short for my portfolio
my_port = yf.download(start=start_date, end=end_date, tickers=my_tickers)

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[                       0%%                      ]c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[**************        29%%                      ]  2 of 7 completedc:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[********************* 43%%                      ]  3 of 7 completedc:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[**********************57%%*                     ]  4 of 7 completedc:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  7 of 7 completed

In [3]:
## And review the data:
my_port.head()

Price       Adj Close                                                        \
Ticker            CRM         F        HPQ      LNVGY        TGT       TSLA
Date
2014-03-03  61.490002  9.222396  10.014837  13.908525  46.635639  16.704000
2014-03-04  63.070000  9.325540  10.146213  13.837984  46.161449  16.989332
2014-03-05  63.680000  9.483292  10.085577  13.504541  45.612000  16.844000
2014-03-06  63.139999  9.507560  10.136107  13.754624  45.717384  16.862667
2014-03-07  60.740002  9.477224  10.220323  13.626375  45.724895  16.414000

Price                      Close                    ...       Open             \
Ticker            WMT        CRM      F        HPQ  ...        TGT       TSLA
Date                                                ...
2014-03-03  19.969053  61.490002  15.20  13.501362  ...  61.939999  15.817333
2014-03-04  20.241159  63.070000  15.37  13.678474  ...  62.509998  17.232000
2014-03-05  20.152248  63.680000  15.63  13.596730  ...  61.650002  17.114668
2014-03-06  20.173809  63.139999  15.67  13.664850  ...  60.610001  16.942667
2014-03-07  20.222616  60.740002  15.62  13.778383  ...  60.840000  16.862667

Price                    Volume                                       \
Ticker            WMT       CRM         F       HPQ   LNVGY      TGT
Date
2014-03-03  24.830000   9303400  42824000  27428112  132600  6813300
2014-03-04  24.923332   7927200  33071700  29367413  116000  6400100
2014-03-05  25.106667   5464400  32955900  14328854   97200  7421100
2014-03-06  24.953333   3958800  26630800  15711710   90900  4835100
2014-03-07  24.986668  11239300  23666900  20446451   61400  3817500

Price
Ticker           TSLA       WMT
Date
2014-03-03  196339500  16042800
2014-03-04  131184000  22631400
2014-03-05   89035500  16574400
2014-03-06  110416500  15319800
2014-03-07  117184500  15163800

[5 rows x 42 columns]

In [4]:
## We may only need one index of the multi-index that was returned (Adj Close)
my_port = my_port['Adj Close']

my_port.head()

Ticker,CRM,F,HPQ,LNVGY,TGT,TSLA,WMT
Date,,,,,,,
2014-03-03,61.490002,9.222396,10.014837,13.908525,46.635639,16.704000,19.969053
2014-03-04,63.070000,9.325540,10.146213,13.837984,46.161449,16.989332,20.241159
2014-03-05,63.680000,9.483292,10.085577,13.504541,45.612000,16.844000,20.152248
2014-03-06,63.139999,9.507560,10.136107,13.754624,45.717384,16.862667,20.173809
2014-03-07,60.740002,9.477224,10.220323,13.626375,45.724895,16.414000,20.222616

In [5]:

my_port_table = pd.DataFrame(index = my_tickers)

In [6]:
## Calculation for 1a. and 1b. in the 1st project. Column of the tickers and portfolio weights.

port_weight = [1/len(my_tickers)] * len(my_tickers)
my_port_table['Portfolio_Weight'] = port_weight

my_port_table

       Portfolio_Weight
CRM            0.142857
HPQ            0.142857
LNVGY          0.142857
F              0.142857
TSLA           0.142857
WMT            0.142857
TGT            0.142857

In [7]:
## Calculation for 1c. 
def get_stock_prices(my_tickers, start_date, end_date):
    my_port
    return my_port

stock_prices = get_stock_prices(my_tickers, start_date, end_date)
returns_3months = stock_prices.pct_change().rolling(window=63).sum().dropna()
volatility = returns_3months.std() * (252 ** 0.5)
result_df = pd.DataFrame({'Ticker': my_tickers, 'Volatility': volatility})

print(result_df)

       Ticker  Volatility
Ticker
CRM       CRM    2.187935
F         HPQ    2.759284
HPQ     LNVGY    2.193061
LNVGY       F    3.032248
TGT      TSLA    2.322772
TSLA      WMT    4.588262
WMT       TGT    1.347638

In [8]:
my_port_table['Annualized Volatility'] = volatility
my_port_table

       Portfolio_Weight  Annualized Volatility
CRM            0.142857               2.187935
HPQ            0.142857               2.193061
LNVGY          0.142857               3.032248
F              0.142857               2.759284
TSLA           0.142857               4.588262
WMT            0.142857               1.347638
TGT            0.142857               2.322772

In [9]:
## Calculation for 1d.

## First download Adjusted Close Price data for S&P 500 ETF
spy = yf.download(start=start_date, end=end_date, tickers='SPY')
spy = spy['Adj Close']

## Combine portfolio and SPY data into a single DataFrame
my_port_and_spy_data = pd.concat([my_port, spy], axis=1)
my_port_and_spy_data.columns = my_tickers + ['SPY']

## Calculate daily returns
my_port_and_spy__d_returns = my_port_and_spy_data.pct_change().dropna()

## Calculate covariance matrix
my_port_and_spy_cov_matrix = my_port_and_spy__d_returns.cov()

## Extract covariances with SPY
cov_with_spy = my_port_and_spy_cov_matrix['SPY'].drop('SPY')

## Calculate SPY variance
spy_variance = my_port_and_spy_cov_matrix.loc['SPY', 'SPY']

# Calculate beta
betas_spy = cov_with_spy / spy_variance

spy_beta_table = pd.DataFrame({'Tickers': my_tickers, 'Beta': betas_spy})
print(spy_beta_table)


'''
## Then calculate the daily returns of portfolio and S&P 500 ETF
my_port_d_returns = prices.pct_change().dropna()
spy_d_returns = spy.pct_change().dropna()

covariances = my_port_d_returns.covwith(spy_d_returns)
'''

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

      Tickers      Beta
CRM       CRM  1.270962
HPQ       HPQ  1.185191
LNVGY   LNVGY  1.209407
F           F  0.649588
TSLA     TSLA  0.823753
WMT       WMT  1.472450
TGT       TGT  0.525543

'\n## Then calculate the daily returns of portfolio and S&P 500 ETF\nmy_port_d_returns = prices.pct_change().dropna()\nspy_d_returns = spy.pct_change().dropna()\n\ncovariances = my_port_d_returns.covwith(spy_d_returns)\n'

In [10]:
## Resulting table after calculating 1d. 
my_port_table['Beta against SPY'] = betas_spy
my_port_table

       Portfolio_Weight  Annualized Volatility  Beta against SPY
CRM            0.142857               2.187935          1.270962
HPQ            0.142857               2.193061          1.185191
LNVGY          0.142857               3.032248          1.209407
F              0.142857               2.759284          0.649588
TSLA           0.142857               4.588262          0.823753
WMT            0.142857               1.347638          1.472450
TGT            0.142857               2.322772          0.525543

In [11]:
## Calculation for 1e.

## First download Adjusted Close Price data for S&P 500 ETF
iwm = yf.download(start=start_date, end=end_date, tickers='IWM')
iwm = iwm['Adj Close']

## Combine portfolio and IWM data into a single DataFrame
my_port_and_iwm_data = pd.concat([my_port, iwm], axis=1)
my_port_and_iwm_data.columns = my_tickers + ['IWM']

## Calculate daily returns
my_port_and_iwm__d_returns = my_port_and_iwm_data.pct_change().dropna()

## Calculate covariance matrix
my_port_and_iwm_cov_matrix = my_port_and_iwm__d_returns.cov()

## Extract covariances with IWM
cov_with_iwm = my_port_and_iwm_cov_matrix['IWM'].drop('IWM')

## Calculate IWM variance
iwm_variance = my_port_and_iwm_cov_matrix.loc['IWM', 'IWM']

# Calculate beta
betas_iwm = cov_with_iwm / iwm_variance

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

In [12]:
## Resulting table after calculating 1e.
my_port_table['Beta against IWM'] = betas_iwm
my_port_table

,Portfolio_Weight,Annualized Volatility,Beta against SPY,Beta against IWM
CRM,0.142857,2.187935,1.270962,0.879653
HPQ,0.142857,2.193061,1.185191,1.002728
LNVGY,0.142857,3.032248,1.209407,0.937631
F,0.142857,2.759284,0.649588,0.501481
TSLA,0.142857,4.588262,0.823753,0.600905
WMT,0.142857,1.347638,1.472450,1.128934
TGT,0.142857,2.322772,0.525543,0.297547

In [13]:
## Calculation for 1f.

## First download Adjusted Close Price data for DIA
dia = yf.download(start=start_date, end=end_date, tickers='DIA')
dia = dia['Adj Close']

## Combine portfolio and DIA data into a single DataFrame
my_port_and_dia_data = pd.concat([my_port, dia], axis=1)
my_port_and_dia_data.columns = my_tickers + ['DIA']

## Calculate daily returns
my_port_and_dia__d_returns = my_port_and_dia_data.pct_change().dropna()

## Calculate covariance matrix
my_port_and_dia_cov_matrix = my_port_and_dia__d_returns.cov()

## Extract covariances with IWM
cov_with_dia = my_port_and_dia_cov_matrix['DIA'].drop('DIA')

## Calculate DIA variance
dia_variance = my_port_and_dia_cov_matrix.loc['DIA', 'DIA']

# Calculate beta
betas_dia = cov_with_dia / dia_variance

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

In [14]:
## Resulting table after calculating 1f.
my_port_table['Beta against DIA'] = betas_dia
my_port_table

,Portfolio_Weight,Annualized Volatility,Beta against SPY,Beta against IWM,Beta against DIA
CRM,0.142857,2.187935,1.270962,0.879653,1.132744
HPQ,0.142857,2.193061,1.185191,1.002728,1.205732
LNVGY,0.142857,3.032248,1.209407,0.937631,1.204828
F,0.142857,2.759284,0.649588,0.501481,0.610798
TSLA,0.142857,4.588262,0.823753,0.600905,0.805076
WMT,0.142857,1.347638,1.472450,1.128934,1.242411
TGT,0.142857,2.322772,0.525543,0.297547,0.544767

In [24]:
## Calculation of 1g.

## First, calculate the 52 week low.
# Create an empty DataFrame to store the data
my_port_table = pd.DataFrame()


# Fetch historical data for each stock
for ticker in my_tickers:
    stock = yf.Ticker(ticker)
    historical_data = stock.history(period='1y')  # Fetch 1-year historical data
    my_port_table[ticker] = historical_data['Low']

# Calculate the 52-week low for each stock
my_port_table['52-week Low'] = my_port_table.min(axis=1)

print(my_port_table[['52-week Low']])

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')

                           52-week Low
Date
2023-02-28 00:00:00-05:00    11.250397
2023-03-01 00:00:00-05:00    11.400278
2023-03-02 00:00:00-05:00    11.456482
2023-03-03 00:00:00-05:00    11.849919
2023-03-06 00:00:00-05:00    12.112210
...                                ...
2024-02-22 00:00:00-05:00    12.050000
2024-02-23 00:00:00-05:00    12.090000
2024-02-26 00:00:00-05:00    11.950000
2024-02-27 00:00:00-05:00    11.960000
2024-02-28 00:00:00-05:00    11.955000

[252 rows x 1 columns]

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')

In [25]:

## Then calculate 52-week high 
# Fetch historical data for each stock
for ticker in my_tickers:
    stock = yf.Ticker(ticker)
    historical_data = stock.history(period='1y')  # Fetch 1-year historical data
    my_port_table[ticker] = historical_data['High']

# Calculate the 52-week low for each stock
my_port_table['52-week High'] = my_port_table.max(axis=1)

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')

In [26]:
## Now calculate the Average Weekly Drawdown, (52-week Low minus 52-week High) / 52-week High
av__w_drawdown = ((my_port_table['52-week Low'] - my_port_table['52-week High']) / my_port_table['52-week High']) * 100

In [30]:

my_port_table = pd.DataFrame(av__w_drawdown, columns=['Average Weekly Drawdown'], index=my_tickers)
my_port_table

       Average Weekly Drawdown
CRM                        NaN
HPQ                        NaN
LNVGY                      NaN
F                          NaN
TSLA                       NaN
WMT                        NaN
TGT                        NaN

In [16]:
## Calculation of 2a. and 2b.
'''
# Assuming you have two sets of data representing the ETF and another asset/index

etf_tickers = ['SPY','DIA','IWM']

etf_data = yf.download (start=start_date,end=end_date,tickers=etf_tickers )

etf_data =  etf_data['Adj Close']

def get_etf_prices(etf_tickers,start_date,end_date):
  etf_data
  return etf_data

etf_prices = get_etf_prices(etf_tickers,start_date,end_date)



# Create a DataFrame with the data
all_tickers = my_tickers.extend(etf_tickers)

port_and_etf_data = {'ETF': etf_prices, 'Stock Prices': stock_prices}

etf_table = pd.DataFrame(port_and_etf_data).set_index('{Port_and_Etf_Tickers')


etf_table = pd.DataFrame(etf_data, columns= ['ETF Adj Close Prices'], index=etf_tickers)
etf_table
'''

"\n# Assuming you have two sets of data representing the ETF and another asset/index\n\netf_tickers = ['SPY','DIA','IWM']\n\netf_data = yf.download (start=start_date,end=end_date,tickers=etf_tickers )\n\netf_data =  etf_data['Adj Close']\n\ndef get_etf_prices(etf_tickers,start_date,end_date):\n  etf_data\n  return etf_data\n\netf_prices = get_etf_prices(etf_tickers,start_date,end_date)\n\n\n\n# Create a DataFrame with the data\nall_tickers = my_tickers.extend(etf_tickers)\n\nport_and_etf_data = {'ETF': etf_prices, 'Stock Prices': stock_prices}\n\netf_table = pd.DataFrame(port_and_etf_data).set_index('{Port_and_Etf_Tickers')\n\n\netf_table = pd.DataFrame(etf_data, columns= ['ETF Adj Close Prices'], index=etf_tickers)\netf_table\n"

In [17]:

## Calculation for 3
'''
ETF_tickers = ['SPY', 'IWM', 'DIA']
ETF_data = yf.download(start=start_date, end=end_date, tickers=ETF_tickers)
ETF_data.head()
ETF_data = ETF_data['Adj Close']
ETF_data.head()

Port_and_ETF_data = {
    'portfolio data': my_port,
     'ETF data': ETF_data
}

All_Tickers = my_tickers.extend(ETF_tickers)
print(All_Tickers)

'''

"\nETF_tickers = ['SPY', 'IWM', 'DIA']\nETF_data = yf.download(start=start_date, end=end_date, tickers=ETF_tickers)\nETF_data.head()\nETF_data = ETF_data['Adj Close']\nETF_data.head()\n\nPort_and_ETF_data = {\n    'portfolio data': my_port,\n     'ETF data': ETF_data\n}\n\nAll_Tickers = my_tickers.extend(ETF_tickers)\nprint(All_Tickers)\n\n"

In [18]:
'''
Port_and_ETF_table = pd.DataFrame(Port_and_ETF_data)
ETF_table = pd.DataFrame(ETF_data,columns=['Adj Close'], index=ETF_tickers)
ETF_table
'''

"\nPort_and_ETF_table = pd.DataFrame(Port_and_ETF_data)\nETF_table = pd.DataFrame(ETF_data,columns=['Adj Close'], index=ETF_tickers)\nETF_table\n"