In [37]:
import pandas as pd
import yfinance as yf
import datetime as dt

# list of assets (updated with our chosen assets):
# Companies: Salesforce, HP, Lenovo, Ford, Tesla, Walmart, Target 
my_tickers = ['CRM', 'HPQ', 'LNVGY', 'F', 'TSLA', 'WMT', 'TGT']


# Assign a start date and end date for the data download, 1 year of data
start_date = dt.datetime.today() - pd.Timedelta(400, "d")
end_date = dt.datetime.today()

In [38]:
## Now download the data using the above variables, my_port is short for my portfolio
my_port = yf.download(start=start_date, end=end_date, tickers=my_tickers)

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[                       0%%                      ]c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[**************        29%%                      ]  2 of 7 completedc:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[**************        29%%                      ]  2 of 7 completedc:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[**************        29%%                      ]  2 of 7 completedc:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  7 of 7 completed

In [39]:
## And review the data:
my_port.head()

Price        Adj Close                                               \
Ticker             CRM          F        HPQ      LNVGY         TGT
Date
2023-01-30  164.750000  11.358669  27.801153  15.126039  162.192490
2023-01-31  167.970001  11.905012  28.109840  15.346228  165.519424
2023-02-01  171.820007  12.151749  28.814035  15.528122  170.269455
2023-02-02  174.639999  12.618785  29.701511  15.451535  174.057922
2023-02-03  171.039993  11.658276  29.431410  15.566417  169.961746

Price                                   Close                    ...  \
Ticker            TSLA        WMT         CRM      F        HPQ  ...
Date                                                             ...
2023-01-30  166.660004  46.671459  164.750000  12.89  28.820000  ...
2023-01-31  173.220001  47.236183  167.970001  13.51  29.139999  ...
2023-02-01  181.410004  47.498840  171.820007  13.79  29.870001  ...
2023-02-02  188.270004  47.154102  174.639999  14.32  30.790001  ...
2023-02-03  189.979996  46.527000  171.039993  13.23  30.510000  ...

Price             Open                           Volume                      \
Ticker             TGT        TSLA        WMT       CRM          F      HPQ
Date
2023-01-30  167.000000  178.050003  47.373333   8169800   64512600  4727800
2023-01-31  168.119995  164.570007  47.439999   6421300   83093300  5884100
2023-02-01  172.110001  173.889999  47.886665   8853900   70641000  5698700
2023-02-02  177.710007  187.330002  48.136665  10667100  102579800  6461300
2023-02-03  177.270004  183.949997  47.786667   6481700  165500200  4339300

Price
Ticker      LNVGY      TGT       TSLA       WMT
Date
2023-01-30  18700  3453500  230878800  15897600
2023-01-31  34300  3716000  196813500  14103600
2023-02-01  30800  4022200  213806300  12849300
2023-02-02  35000  4003800  217448300  17806800
2023-02-03  26300  2941600  232662000  17155500

[5 rows x 42 columns]

In [40]:
## We may only need one index of the multi-index that was returned (Adj Close)
my_port = my_port['Adj Close']

my_port.head()

Ticker,CRM,F,HPQ,LNVGY,TGT,TSLA,WMT
Date,,,,,,,
2023-01-30,164.750000,11.358669,27.801153,15.126039,162.192490,166.660004,46.671459
2023-01-31,167.970001,11.905012,28.109840,15.346228,165.519424,173.220001,47.236183
2023-02-01,171.820007,12.151749,28.814035,15.528122,170.269455,181.410004,47.498840
2023-02-02,174.639999,12.618785,29.701511,15.451535,174.057922,188.270004,47.154102
2023-02-03,171.039993,11.658276,29.431410,15.566417,169.961746,189.979996,46.527000

In [41]:

my_port_table = pd.DataFrame(index = my_tickers)

In [42]:
## Calculation for 1a. and 1b. in the 1st project. Column of the tickers and portfolio weights.

port_weight = [1/len(my_tickers)] * len(my_tickers)
my_port_table['Portfolio_Weight'] = port_weight

my_port_table

       Portfolio_Weight
CRM            0.142857
HPQ            0.142857
LNVGY          0.142857
F              0.142857
TSLA           0.142857
WMT            0.142857
TGT            0.142857

In [43]:
## Calculation for 1c. 
def get_stock_prices(my_tickers, start_date, end_date):
    my_port
    return my_port

stock_prices = get_stock_prices(my_tickers, start_date, end_date)
returns_3months = stock_prices.pct_change().rolling(window=63).sum().dropna()
volatility = returns_3months.std() * (252 ** 0.5)
result_df = pd.DataFrame({'Ticker': my_tickers, 'Volatility': volatility})

print(result_df)

       Ticker  Volatility
Ticker
CRM       CRM    2.056421
F         HPQ    2.336933
HPQ     LNVGY    1.737389
LNVGY       F    1.879651
TGT      TSLA    2.954088
TSLA      WMT    3.448031
WMT       TGT    0.725252

In [44]:
my_port_table['Annualized Volatility'] = volatility
my_port_table

       Portfolio_Weight  Annualized Volatility
CRM            0.142857               2.056421
HPQ            0.142857               1.737389
LNVGY          0.142857               1.879651
F              0.142857               2.336933
TSLA           0.142857               3.448031
WMT            0.142857               0.725252
TGT            0.142857               2.954088

In [45]:
## Calculation for 1d.

## First download Adjusted Close Price data for S&P 500 ETF
spy = yf.download(start=start_date, end=end_date, tickers='SPY')
spy = spy['Adj Close']

## Combine portfolio and SPY data into a single DataFrame
my_port_and_spy_data = pd.concat([my_port, spy], axis=1)
my_port_and_spy_data.columns = my_tickers + ['SPY']

## Calculate daily returns
my_port_and_spy__d_returns = my_port_and_spy_data.pct_change().dropna()

## Calculate covariance matrix
my_port_and_spy_cov_matrix = my_port_and_spy__d_returns.cov()

## Extract covariances with SPY
cov_with_spy = my_port_and_spy_cov_matrix['SPY'].drop('SPY')

## Calculate SPY variance
spy_variance = my_port_and_spy_cov_matrix.loc['SPY', 'SPY']

# Calculate beta
betas_spy = cov_with_spy / spy_variance

spy_beta_table = pd.DataFrame({'Tickers': my_tickers, 'Beta': betas_spy})
print(spy_beta_table)


'''
## Then calculate the daily returns of portfolio and S&P 500 ETF
my_port_d_returns = prices.pct_change().dropna()
spy_d_returns = spy.pct_change().dropna()

covariances = my_port_d_returns.covwith(spy_d_returns)
'''

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

      Tickers      Beta
CRM       CRM  1.274608
HPQ       HPQ  1.391914
LNVGY   LNVGY  1.015285
F           F  0.626841
TSLA     TSLA  0.831591
WMT       WMT  2.014543
TGT       TGT  0.310214

'\n## Then calculate the daily returns of portfolio and S&P 500 ETF\nmy_port_d_returns = prices.pct_change().dropna()\nspy_d_returns = spy.pct_change().dropna()\n\ncovariances = my_port_d_returns.covwith(spy_d_returns)\n'

In [46]:
## Resulting table after calculating 1d. 
my_port_table['Beta against SPY'] = betas_spy
my_port_table

       Portfolio_Weight  Annualized Volatility  Beta against SPY
CRM            0.142857               2.056421          1.274608
HPQ            0.142857               1.737389          1.391914
LNVGY          0.142857               1.879651          1.015285
F              0.142857               2.336933          0.626841
TSLA           0.142857               3.448031          0.831591
WMT            0.142857               0.725252          2.014543
TGT            0.142857               2.954088          0.310214

In [47]:
## Calculation for 1e.

## First download Adjusted Close Price data for S&P 500 ETF
iwm = yf.download(start=start_date, end=end_date, tickers='IWM')
iwm = iwm['Adj Close']

## Combine portfolio and IWM data into a single DataFrame
my_port_and_iwm_data = pd.concat([my_port, iwm], axis=1)
my_port_and_iwm_data.columns = my_tickers + ['IWM']

## Calculate daily returns
my_port_and_iwm__d_returns = my_port_and_iwm_data.pct_change().dropna()

## Calculate covariance matrix
my_port_and_iwm_cov_matrix = my_port_and_iwm__d_returns.cov()

## Extract covariances with IWM
cov_with_iwm = my_port_and_iwm_cov_matrix['IWM'].drop('IWM')

## Calculate IWM variance
iwm_variance = my_port_and_iwm_cov_matrix.loc['IWM', 'IWM']

# Calculate beta
betas_iwm = cov_with_iwm / iwm_variance

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

In [48]:
## Resulting table after calculating 1e.
my_port_table['Beta against IWM'] = betas_iwm
my_port_table

,Portfolio_Weight,Annualized Volatility,Beta against SPY,Beta against IWM
CRM,0.142857,2.056421,1.274608,0.567836
HPQ,0.142857,1.737389,1.391914,0.966242
LNVGY,0.142857,1.879651,1.015285,0.620123
F,0.142857,2.336933,0.626841,0.514443
TSLA,0.142857,3.448031,0.831591,0.620166
WMT,0.142857,0.725252,2.014543,1.063905
TGT,0.142857,2.954088,0.310214,0.132905

In [49]:
## Calculation for 1f.

## First download Adjusted Close Price data for DIA
dia = yf.download(start=start_date, end=end_date, tickers='DIA')
dia = dia['Adj Close']

## Combine portfolio and DIA data into a single DataFrame
my_port_and_dia_data = pd.concat([my_port, dia], axis=1)
my_port_and_dia_data.columns = my_tickers + ['DIA']

## Calculate daily returns
my_port_and_dia__d_returns = my_port_and_dia_data.pct_change().dropna()

## Calculate covariance matrix
my_port_and_dia_cov_matrix = my_port_and_dia__d_returns.cov()

## Extract covariances with IWM
cov_with_dia = my_port_and_dia_cov_matrix['DIA'].drop('DIA')

## Calculate DIA variance
dia_variance = my_port_and_dia_cov_matrix.loc['DIA', 'DIA']

# Calculate beta
betas_dia = cov_with_dia / dia_variance

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

In [50]:
## Resulting table after calculating 1f.
my_port_table['Beta against DIA'] = betas_dia
my_port_table

,Portfolio_Weight,Annualized Volatility,Beta against SPY,Beta against IWM,Beta against DIA
CRM,0.142857,2.056421,1.274608,0.567836,1.320845
HPQ,0.142857,1.737389,1.391914,0.966242,1.666240
LNVGY,0.142857,1.879651,1.015285,0.620123,1.115896
F,0.142857,2.336933,0.626841,0.514443,0.649892
TSLA,0.142857,3.448031,0.831591,0.620166,1.104466
WMT,0.142857,0.725252,2.014543,1.063905,1.779189
TGT,0.142857,2.954088,0.310214,0.132905,0.441029

In [51]:
## Calculation of 1g., Average Weekly Drawdown, (52-week Low minus 52-week High) / 52-week High

av_w_drawdown = (my_port.rolling(5).min() - my_port.rolling(5).max()).mean() 

my_port_table['Average Weekly Drawdown'] = av_w_drawdown 
my_port_table

,Portfolio_Weight,Annualized Volatility,Beta against SPY,Beta against IWM,Beta against DIA,Average Weekly Drawdown
CRM,0.142857,2.056421,1.274608,0.567836,1.320845,-8.079119
HPQ,0.142857,1.737389,1.391914,0.966242,1.666240,-0.936431
LNVGY,0.142857,1.879651,1.015285,0.620123,1.115896,-1.198414
F,0.142857,2.336933,0.626841,0.514443,0.649892,-0.523257
TSLA,0.142857,3.448031,0.831591,0.620166,1.104466,-14.803566
WMT,0.142857,0.725252,2.014543,1.063905,1.779189,-1.015525
TGT,0.142857,2.954088,0.310214,0.132905,0.441029,-4.883310

In [52]:
## Calculation of 1h., Maximum Weekly Drawdown (52-week Low minus 52-week High) / 52-week High
max_w_drawdown = (my_port.rolling(5).min() - my_port.rolling(5).max()).max()

my_port_table['Maximum Weekly Drawdown'] = max_w_drawdown 
my_port_table

,Portfolio_Weight,Annualized Volatility,Beta against SPY,Beta against IWM,Beta against DIA,Average Weekly Drawdown,Maximum Weekly Drawdown
CRM,0.142857,2.056421,1.274608,0.567836,1.320845,-8.079119,-0.880005
HPQ,0.142857,1.737389,1.391914,0.966242,1.666240,-0.936431,-0.148636
LNVGY,0.142857,1.879651,1.015285,0.620123,1.115896,-1.198414,-0.124456
F,0.142857,2.336933,0.626841,0.514443,0.649892,-0.523257,-0.105467
TSLA,0.142857,3.448031,0.831591,0.620166,1.104466,-14.803566,-3.029999
WMT,0.142857,0.725252,2.014543,1.063905,1.779189,-1.015525,-0.188625
TGT,0.142857,2.954088,0.310214,0.132905,0.441029,-4.883310,-0.793396

In [53]:
## Calculation of 1i., Total Return (using trailing 10-years)

start_date = dt.datetime.today() - pd.Timedelta(3650, "d")  # First, put 3650, which represents 10 years from today.
my_port = yf.download(start=start_date, end=end_date, tickers=my_tickers)  # Then download data for 10 years
my_port = my_port['Adj Close']
t_return = my_port.pct_change().sum()[-20:] # Calculate the yearly returns for each stock, then add up the yearly returns of each stock, then only take into account the last 20 days of data for a trailing calculation
t_return

c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[                       0%%                      ]c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[**********************57%%*                     ]  4 of 7 completedc:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\samue\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  7 of 7 completed

Ticker
CRM      2.203994
F        0.893492
HPQ      1.622868
LNVGY    1.307860
TGT      1.768618
TSLA     3.955372
WMT      1.306476
dtype: float64

In [54]:
## Table with 1i included.
my_port_table['Total Return'] = t_return
my_port_table

,Portfolio_Weight,Annualized Volatility,Beta against SPY,Beta against IWM,Beta against DIA,Average Weekly Drawdown,Maximum Weekly Drawdown,Total Return
CRM,0.142857,2.056421,1.274608,0.567836,1.320845,-8.079119,-0.880005,2.203994
HPQ,0.142857,1.737389,1.391914,0.966242,1.666240,-0.936431,-0.148636,1.622868
LNVGY,0.142857,1.879651,1.015285,0.620123,1.115896,-1.198414,-0.124456,1.307860
F,0.142857,2.336933,0.626841,0.514443,0.649892,-0.523257,-0.105467,0.893492
TSLA,0.142857,3.448031,0.831591,0.620166,1.104466,-14.803566,-3.029999,3.955372
WMT,0.142857,0.725252,2.014543,1.063905,1.779189,-1.015525,-0.188625,1.306476
TGT,0.142857,2.954088,0.310214,0.132905,0.441029,-4.883310,-0.793396,1.768618

In [55]:
## Calculation of 1j., Annualized Total Return (using trailing 10-years)

t_return_ann = ((my_port.pct_change().sum()[-20:] + 1) ** 252) - 1 
t_return_ann

Ticker
CRM      2.718263e+127
F         7.419965e+69
HPQ      3.401269e+105
LNVGY     3.378942e+91
TGT      2.820331e+111
TSLA     1.442820e+175
WMT       2.904803e+91
dtype: float64

In [56]:
## Stock porfolio table with 1j included.
my_port_table['Annualized Total Return'] = t_return_ann
my_port_table

,Portfolio_Weight,Annualized Volatility,Beta against SPY,Beta against IWM,Beta against DIA,Average Weekly Drawdown,Maximum Weekly Drawdown,Total Return,Annualized Total Return
CRM,0.142857,2.056421,1.274608,0.567836,1.320845,-8.079119,-0.880005,2.203994,2.718263e+127
HPQ,0.142857,1.737389,1.391914,0.966242,1.666240,-0.936431,-0.148636,1.622868,3.401269e+105
LNVGY,0.142857,1.879651,1.015285,0.620123,1.115896,-1.198414,-0.124456,1.307860,3.378942e+91
F,0.142857,2.336933,0.626841,0.514443,0.649892,-0.523257,-0.105467,0.893492,7.419965e+69
TSLA,0.142857,3.448031,0.831591,0.620166,1.104466,-14.803566,-3.029999,3.955372,1.442820e+175
WMT,0.142857,0.725252,2.014543,1.063905,1.779189,-1.015525,-0.188625,1.306476,2.904803e+91
TGT,0.142857,2.954088,0.310214,0.132905,0.441029,-4.883310,-0.793396,1.768618,2.820331e+111

In [57]:
## The code below was another way that we tried to calculate the Average Weekly Drawdown, 1g.

In [58]:
'''
## Calculation of 1g., Average Weekly Drawdown, (52-week Low minus 52-week High) / 52-week High

## First, calculate the 52 week low.

# Create an empty DataFrame to store the data
my_port_table = pd.DataFrame()


# Fetch historical data for each stock
for ticker in my_tickers:
    stock = yf.Ticker(ticker)
    historical_data = stock.history(period='1y')  # Fetch 1-year historical data
    my_port_table[ticker] = historical_data['Low']

# Calculate the 52-week low for each stock
my_port_table['52-week Low'] = my_port_table.min(axis=1)

print(my_port_table[['52-week Low']])
'''

"\n## Calculation of 1g., Average Weekly Drawdown, (52-week Low minus 52-week High) / 52-week High\n\n## First, calculate the 52 week low.\n\n# Create an empty DataFrame to store the data\nmy_port_table = pd.DataFrame()\n\n\n# Fetch historical data for each stock\nfor ticker in my_tickers:\n    stock = yf.Ticker(ticker)\n    historical_data = stock.history(period='1y')  # Fetch 1-year historical data\n    my_port_table[ticker] = historical_data['Low']\n\n# Calculate the 52-week low for each stock\nmy_port_table['52-week Low'] = my_port_table.min(axis=1)\n\nprint(my_port_table[['52-week Low']])\n"

In [59]:

'''
## Then calculate 52-week high 
# Fetch historical data for each stock
for ticker in my_tickers:
    stock = yf.Ticker(ticker)
    historical_data = stock.history(period='1y')  # Fetch 1-year historical data
    my_port_table[ticker] = historical_data['High']

# Calculate the 52-week low for each stock
my_port_table['52-week High'] = my_port_table.max(axis=1)
'''

"\n## Then calculate 52-week high \n# Fetch historical data for each stock\nfor ticker in my_tickers:\n    stock = yf.Ticker(ticker)\n    historical_data = stock.history(period='1y')  # Fetch 1-year historical data\n    my_port_table[ticker] = historical_data['High']\n\n# Calculate the 52-week low for each stock\nmy_port_table['52-week High'] = my_port_table.max(axis=1)\n"

In [60]:
'''
## Now calculate the Average Weekly Drawdown, (52-week Low minus 52-week High) / 52-week High
av__w_drawdown = ((my_port_table['52-week Low'] - my_port_table['52-week High']) / my_port_table['52-week High']) * 100
'''

"\n## Now calculate the Average Weekly Drawdown, (52-week Low minus 52-week High) / 52-week High\nav__w_drawdown = ((my_port_table['52-week Low'] - my_port_table['52-week High']) / my_port_table['52-week High']) * 100\n"

In [61]:
'''
my_port_table = pd.DataFrame(av__w_drawdown, columns=['Average Weekly Drawdown'], index=my_tickers)
my_port_table
'''

"\nmy_port_table = pd.DataFrame(av__w_drawdown, columns=['Average Weekly Drawdown'], index=my_tickers)\nmy_port_table\n"

In [62]:

## This is how we attempted to calculate the values for number 3 in the project.
'''
ETF_tickers = ['SPY', 'IWM', 'DIA']
ETF_data = yf.download(start=start_date, end=end_date, tickers=ETF_tickers)
ETF_data.head()
ETF_data = ETF_data['Adj Close']
ETF_data.head()

Port_and_ETF_data = {
    'portfolio data': my_port,
     'ETF data': ETF_data
}

All_Tickers = my_tickers.extend(ETF_tickers)
print(All_Tickers)

'''

"\nETF_tickers = ['SPY', 'IWM', 'DIA']\nETF_data = yf.download(start=start_date, end=end_date, tickers=ETF_tickers)\nETF_data.head()\nETF_data = ETF_data['Adj Close']\nETF_data.head()\n\nPort_and_ETF_data = {\n    'portfolio data': my_port,\n     'ETF data': ETF_data\n}\n\nAll_Tickers = my_tickers.extend(ETF_tickers)\nprint(All_Tickers)\n\n"

In [63]:
'''
Port_and_ETF_table = pd.DataFrame(Port_and_ETF_data)
ETF_table = pd.DataFrame(ETF_data,columns=['Adj Close'], index=ETF_tickers)
ETF_table
'''

"\nPort_and_ETF_table = pd.DataFrame(Port_and_ETF_data)\nETF_table = pd.DataFrame(ETF_data,columns=['Adj Close'], index=ETF_tickers)\nETF_table\n"